name: Daily Bot Run

on:
  schedule:
    - cron: '25 3 * * 1-5'  # Runs at 8:55 AM IST (3:25 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: python bot.py
